services:
    # Controllers
    _instanceof:
        Netgen\TagsBundle\Controller\Admin\Controller:
            autowire: true
            tags:
                - 'controller.service_arguments'
                - 'container.service_subscriber'

    netgen_tags.admin.controller.tag:
        class: Netgen\TagsBundle\Controller\Admin\TagController
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@ibexa.api.service.content_type"
            - "@netgen_tags.pagerfanta.children_tags_adapter"
            - "@netgen_tags.pagerfanta.search_tags_adapter"

    netgen_tags.admin.controller.related_content:
        class: Netgen\TagsBundle\Controller\Admin\RelatedContentController
        arguments:
            - "@netgen_tags.pagerfanta.related_content_adapter"
            - "@netgen_tags.search.related_content.sort_service"

    netgen_tags.admin.controller.synonym:
        class: Netgen\TagsBundle\Controller\Admin\SynonymController
        arguments:
            - "@netgen_tags.api.service.tags"

    netgen_tags.admin.controller.tree:
        class: Netgen\TagsBundle\Controller\Admin\TreeController
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@translator"
            - "@router"
            - "@ibexa.config.resolver"

    netgen_tags.admin.controller.field:
        class: Netgen\TagsBundle\Controller\Admin\FieldController
        arguments:
            - "@netgen_tags.api.service.tags"
            - "@ibexa.config.resolver"

    netgen_tags.admin.controller.access:
        class: Netgen\TagsBundle\Controller\Admin\AccessController
